import LG21TestOptionalPolicies.ContinuousResampling
import Mathlib.Probability.Kernel.Composition.MeasureComp
import Mathlib.Probability.Kernel.Composition.Prod

/-!
# Source-shaped Gaussian repair for LG21 Definition 6 and Theorem 4.4

The earlier continuous resampling surface accepted an already-packaged
conditional estimate kernel.  This module instead constructs both sides of
Definition 6 from one Gaussian conditional test experiment and one affine
posterior estimator:

* conditioned on the first `K - 1` features, the test is the posterior-base
  mean plus independent centered Gaussian test noise;
* an access student's actual score and a no-access student's synthetic score
  are generated by that same kernel;
* the school applies the same Gaussian posterior-mean formula to either
  score.

The fairness theorem is consequently an equality of the actual access output
measure and the no-access resampling output measure, obtained by the
measure--kernel composition law rather than by postulating equal output
kernels.

This is deliberately a focused repair module.  It models the source's
Gaussian posterior summary after the first `K - 1` features, but does not yet
derive that summary from the paper's full finite feature-noise product law.
-/

namespace LG21TestOptionalPolicies

noncomputable section

open MeasureTheory
open ProbabilityTheory

/--
The Gaussian posterior summary available after the first `K - 1` observed
features.  `posteriorBaseMean` and `posteriorBaseVariance` are the usual
conjugate-Gaussian posterior parameters before observing the optional test.

The source model supplies positive Gaussian variances.  Positivity is recorded
explicitly here because the displayed PBO update divides by their sum.
-/
structure LG21GaussianPBOResamplingSource (Base : Type*)
    [MeasurableSpace Base] where
  /--
  The common law of the first `K - 1` features in the access and no-access
  populations.  This is the source's access-independence bridge, recorded as
  an explicit input rather than inferred from a kernel name.
  -/
  baseLaw : Measure Base
  baseLaw_isProbability : IsProbabilityMeasure baseLaw
  posteriorBaseMean : Base → ℝ
  posteriorBaseMean_measurable : Measurable posteriorBaseMean
  posteriorBaseVariance : NNReal
  posteriorBaseVariance_pos : 0 < (posteriorBaseVariance : ℝ)
  testNoiseVariance : NNReal
  testNoiseVariance_pos : 0 < (testNoiseVariance : ℝ)

/-- Conditional variance of the test score given the first `K - 1` features. -/
def lg21D6ConditionalTestVariance
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : NNReal :=
  S.posteriorBaseVariance + S.testNoiseVariance

/-- The Gaussian posterior weight placed on the test score after it is observed. -/
def lg21D6PosteriorTestWeight
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : ℝ :=
  (S.posteriorBaseVariance : ℝ) /
    ((S.posteriorBaseVariance : ℝ) + (S.testNoiseVariance : ℝ))

/-- The denominator in the PBO update is strictly positive. -/
theorem lg21D6PosteriorVarianceSum_pos
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    0 < (S.posteriorBaseVariance : ℝ) + (S.testNoiseVariance : ℝ) :=
  add_pos S.posteriorBaseVariance_pos S.testNoiseVariance_pos

/-- Independent centered Gaussian test noise, indexed by the base profile. -/
def lg21D6GaussianTestNoiseKernel
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Kernel Base ℝ :=
  Kernel.const Base (gaussianReal 0 (lg21D6ConditionalTestVariance S))

/-- The centered Gaussian noise construction is a Markov kernel. -/
theorem lg21D6GaussianTestNoiseKernel_isMarkov
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    IsMarkovKernel (lg21D6GaussianTestNoiseKernel S) := by
  unfold lg21D6GaussianTestNoiseKernel
  infer_instance

/--
The source conditional test kernel.  It draws one centered Gaussian noise term
and adds it to the posterior mean based on the first `K - 1` features.
-/
def lg21D6ConditionalGaussianTestKernel
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Kernel Base ℝ :=
  (Kernel.id ×ₖ lg21D6GaussianTestNoiseKernel S).map
    (fun pair : Base × ℝ => S.posteriorBaseMean pair.1 + pair.2)

/-- Measurability of the source conditional-test construction. -/
theorem lg21D6ConditionalGaussianTestMap_measurable
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    Measurable (fun pair : Base × ℝ => S.posteriorBaseMean pair.1 + pair.2) :=
  (S.posteriorBaseMean_measurable.comp measurable_fst).add measurable_snd

/-- The generated source conditional-test kernel is Markov. -/
theorem lg21D6ConditionalGaussianTestKernel_isMarkov
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    IsMarkovKernel (lg21D6ConditionalGaussianTestKernel S) := by
  letI : IsMarkovKernel (lg21D6GaussianTestNoiseKernel S) :=
    lg21D6GaussianTestNoiseKernel_isMarkov S
  unfold lg21D6ConditionalGaussianTestKernel
  exact Kernel.IsMarkovKernel.map _
    (lg21D6ConditionalGaussianTestMap_measurable S)

/--
The generated conditional test law is exactly the Gaussian law asserted by
the source model: `theta_K | theta_{<K}` has posterior-base mean and posterior
variance plus test-noise variance.
-/
theorem lg21D6ConditionalGaussianTestKernel_apply
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) (base : Base) :
    lg21D6ConditionalGaussianTestKernel S base =
      gaussianReal (S.posteriorBaseMean base)
        (lg21D6ConditionalTestVariance S) := by
  let f : Base × ℝ → ℝ :=
    fun pair => S.posteriorBaseMean pair.1 + pair.2
  have hf : Measurable f := lg21D6ConditionalGaussianTestMap_measurable S
  letI : IsMarkovKernel (lg21D6GaussianTestNoiseKernel S) :=
    lg21D6GaussianTestNoiseKernel_isMarkov S
  calc
    lg21D6ConditionalGaussianTestKernel S base =
        (gaussianReal 0 (lg21D6ConditionalTestVariance S)).map
          (fun noise => S.posteriorBaseMean base + noise) := by
      ext target htarget
      rw [lg21D6ConditionalGaussianTestKernel, Kernel.map_apply' _ hf base htarget]
      rw [Kernel.id_prod_apply'
        (lg21D6GaussianTestNoiseKernel S) base (hf htarget)]
      rw [lg21D6GaussianTestNoiseKernel, Kernel.const_apply]
      rw [Measure.map_apply (by fun_prop) htarget]
      rfl
    _ = gaussianReal (S.posteriorBaseMean base)
          (lg21D6ConditionalTestVariance S) := by
      simpa using
        (gaussianReal_map_const_add
          (μ := (0 : ℝ))
          (v := lg21D6ConditionalTestVariance S)
          (S.posteriorBaseMean base))

/--
The Gaussian PBO estimator after adding the optional test.  This is the
standard conjugate update `m + w * (theta_K - m)`.
-/
def lg21D6GaussianPBOEstimate
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Base × ℝ → ℝ :=
  fun pair =>
    S.posteriorBaseMean pair.1 +
      lg21D6PosteriorTestWeight S *
        (pair.2 - S.posteriorBaseMean pair.1)

/--
The common conditional variance of the PBO estimate after either an actual or
synthetic test draw.  This is the affine-Gaussian form of Equation (2).
-/
def lg21D6CommonEstimateVariance
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : NNReal :=
  NNReal.mk
      ((lg21D6PosteriorTestWeight S) ^ 2)
      (sq_nonneg (lg21D6PosteriorTestWeight S)) *
    lg21D6ConditionalTestVariance S

/-- Measurability of the affine Gaussian PBO estimator. -/
theorem lg21D6GaussianPBOEstimate_measurable
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    Measurable (lg21D6GaussianPBOEstimate S) := by
  unfold lg21D6GaussianPBOEstimate
  exact
    (S.posteriorBaseMean_measurable.comp measurable_fst).add
      (measurable_const.mul
        (measurable_snd.sub
          (S.posteriorBaseMean_measurable.comp measurable_fst)))

/--
Base-indexed joint kernel for an actual access student's base profile and
realized score.  This is a construction, not a supplied matching kernel.
-/
def lg21D6ActualAccessTestJointKernel
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Kernel Base (Base × ℝ) :=
  Kernel.id ×ₖ lg21D6ConditionalGaussianTestKernel S

/--
Definition 6 access conditional estimate kernel: retain the actual Gaussian
score and apply the PBO estimator to the resulting `(base, score)` pair.
-/
def lg21D6ActualAccessEstimateKernel
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Kernel Base ℝ :=
  (lg21D6ActualAccessTestJointKernel S).map (lg21D6GaussianPBOEstimate S)

/--
Definition 6 no-access conditional estimate kernel: draw a synthetic score
from the *same* conditional Gaussian kernel, then apply the *same* PBO
estimator.  It is constructed from the source joint experiment above.
-/
def lg21D6NoAccessResamplingEstimateKernel
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Kernel Base ℝ :=
  Kernel.deterministic (lg21D6GaussianPBOEstimate S)
      (lg21D6GaussianPBOEstimate_measurable S) ∘ₖ
    lg21D6ActualAccessTestJointKernel S

/-- Definition 6's synthetic-score output branch is a genuine Markov
kernel. This is derived from the Gaussian source construction, rather than
being an unchecked field on a policy record. -/
instance lg21D6NoAccessResamplingEstimateKernel_isMarkov
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    IsMarkovKernel (lg21D6NoAccessResamplingEstimateKernel S) := by
  letI : IsMarkovKernel (lg21D6ConditionalGaussianTestKernel S) :=
    lg21D6ConditionalGaussianTestKernel_isMarkov S
  letI : IsMarkovKernel (lg21D6ActualAccessTestJointKernel S) := by
    unfold lg21D6ActualAccessTestJointKernel
    infer_instance
  unfold lg21D6NoAccessResamplingEstimateKernel
  infer_instance

/-- The no-access resampling law is the conditional Gaussian/PBO pushforward. -/
theorem lg21D6NoAccessResamplingEstimateKernel_apply
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) (base : Base) :
    lg21D6NoAccessResamplingEstimateKernel S base =
      (lg21D6ConditionalGaussianTestKernel S base).map
        (fun score => lg21D6GaussianPBOEstimate S (base, score)) := by
  let pairEstimate : Base × ℝ → ℝ := lg21D6GaussianPBOEstimate S
  have hpairEstimate : Measurable pairEstimate :=
    lg21D6GaussianPBOEstimate_measurable S
  have hscoreEstimate : Measurable (fun score : ℝ => pairEstimate (base, score)) :=
    hpairEstimate.comp (measurable_const.prodMk measurable_id)
  letI : IsMarkovKernel (lg21D6ConditionalGaussianTestKernel S) :=
    lg21D6ConditionalGaussianTestKernel_isMarkov S
  ext target htarget
  rw [lg21D6NoAccessResamplingEstimateKernel,
    Kernel.deterministic_comp_eq_map hpairEstimate,
    lg21D6ActualAccessTestJointKernel,
    Kernel.map_apply' _ hpairEstimate base htarget]
  rw [Kernel.id_prod_apply'
    (lg21D6ConditionalGaussianTestKernel S) base (hpairEstimate htarget)]
  rw [Measure.map_apply hscoreEstimate htarget]
  rfl

/--
The no-access PBO resampling law has the same conditional Gaussian estimate
law stated in the proof of Theorem 4.4.  The mean is the posterior mean from
the first `K - 1` features, and the variance is the affine Gaussian image of
the conditional test variance.
-/
theorem lg21D6NoAccessResamplingEstimateKernel_apply_gaussian
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) (base : Base) :
    lg21D6NoAccessResamplingEstimateKernel S base =
      gaussianReal (S.posteriorBaseMean base)
        (lg21D6CommonEstimateVariance S) := by
  let mean : ℝ := S.posteriorBaseMean base
  let weight : ℝ := lg21D6PosteriorTestWeight S
  have hAffine :
      (fun score : ℝ => lg21D6GaussianPBOEstimate S (base, score)) =
        (fun score : ℝ => (1 - weight) * mean + weight * score) := by
    funext score
    dsimp [lg21D6GaussianPBOEstimate, mean, weight]
    ring
  calc
    lg21D6NoAccessResamplingEstimateKernel S base =
        (lg21D6ConditionalGaussianTestKernel S base).map
          (fun score => lg21D6GaussianPBOEstimate S (base, score)) :=
      lg21D6NoAccessResamplingEstimateKernel_apply S base
    _ = (gaussianReal mean (lg21D6ConditionalTestVariance S)).map
          (fun score => lg21D6GaussianPBOEstimate S (base, score)) := by
      rw [lg21D6ConditionalGaussianTestKernel_apply]
    _ = (gaussianReal mean (lg21D6ConditionalTestVariance S)).map
          (fun score => (1 - weight) * mean + weight * score) := by
      rw [hAffine]
    _ = gaussianReal ((1 - weight) * mean + weight * mean)
          (NNReal.mk (weight ^ 2) (sq_nonneg weight) *
            lg21D6ConditionalTestVariance S) := by
      exact lg21_gaussianReal_map_affine
        mean (lg21D6ConditionalTestVariance S)
        ((1 - weight) * mean) weight
    _ = gaussianReal (S.posteriorBaseMean base)
          (lg21D6CommonEstimateVariance S) := by
      congr 2
      · dsimp [mean, weight]
        ring

/-- Observable fairness is derived from the one source-generated experiment. -/
theorem lg21D6GaussianPBOResampling_observably_fair
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    ∀ base,
      lg21D6ActualAccessEstimateKernel S base =
        lg21D6NoAccessResamplingEstimateKernel S base := by
  intro base
  rw [lg21D6NoAccessResamplingEstimateKernel,
    Kernel.deterministic_comp_eq_map
      (lg21D6GaussianPBOEstimate_measurable S)]
  rfl

/-- The access conditional estimate kernel has the same displayed Gaussian law. -/
theorem lg21D6ActualAccessEstimateKernel_apply_gaussian
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) (base : Base) :
    lg21D6ActualAccessEstimateKernel S base =
      gaussianReal (S.posteriorBaseMean base)
        (lg21D6CommonEstimateVariance S) := by
  rw [lg21D6GaussianPBOResampling_observably_fair S base]
  exact lg21D6NoAccessResamplingEstimateKernel_apply_gaussian S base

/-- Actual joint law of base profiles and realized scores for students with access. -/
def lg21D6ActualAccessTestLaw
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Measure (Base × ℝ) :=
  S.baseLaw ⊗ₘ lg21D6ConditionalGaussianTestKernel S

/-- Actual access output law after observing an actual Gaussian test score. -/
def lg21D6ActualAccessEstimateLaw
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Measure ℝ :=
  (lg21D6ActualAccessTestLaw S).map (lg21D6GaussianPBOEstimate S)

/-- No-access output law after drawing a synthetic conditional Gaussian score. -/
def lg21D6NoAccessResamplingEstimateLaw
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) : Measure ℝ :=
  Measure.bind S.baseLaw (lg21D6NoAccessResamplingEstimateKernel S)

/--
The central Definition 6 law identity.  The actual access output measure is
equal to the no-access resampling output measure because both are generated
from the same source conditional Gaussian kernel and PBO estimator.
-/
theorem lg21D6ActualAccessEstimateLaw_eq_noAccessResamplingEstimateLaw
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    lg21D6ActualAccessEstimateLaw S =
      lg21D6NoAccessResamplingEstimateLaw S := by
  have hestimate : Measurable (lg21D6GaussianPBOEstimate S) :=
    lg21D6GaussianPBOEstimate_measurable S
  letI : IsProbabilityMeasure S.baseLaw := S.baseLaw_isProbability
  letI : IsMarkovKernel (lg21D6ConditionalGaussianTestKernel S) :=
    lg21D6ConditionalGaussianTestKernel_isMarkov S
  unfold lg21D6ActualAccessEstimateLaw lg21D6ActualAccessTestLaw
  unfold lg21D6NoAccessResamplingEstimateLaw
  rw [lg21D6NoAccessResamplingEstimateKernel,
    Kernel.deterministic_comp_eq_map hestimate]
  unfold lg21D6ActualAccessTestJointKernel
  change
    (S.baseLaw ⊗ₘ lg21D6ConditionalGaussianTestKernel S).map
        (lg21D6GaussianPBOEstimate S) =
      ((Kernel.id ×ₖ lg21D6ConditionalGaussianTestKernel S).map
        (lg21D6GaussianPBOEstimate S)) ∘ₘ S.baseLaw
  rw [Measure.compProd_eq_comp_prod]
  exact Measure.map_comp S.baseLaw
    (Kernel.id ×ₖ lg21D6ConditionalGaussianTestKernel S) hestimate

/--
Theorem 4.4 under the source Gaussian/PBO refinement: actual conditional
access and synthetic no-access laws agree, and their full population output
measures are equal.
-/
theorem paper_theorem4_4_source_gaussian_pbo_resampling_fair
    {Base : Type*} [MeasurableSpace Base]
    (S : LG21GaussianPBOResamplingSource Base) :
    (∀ base,
      lg21D6ActualAccessEstimateKernel S base =
        lg21D6NoAccessResamplingEstimateKernel S base) ∧
      lg21D6ActualAccessEstimateLaw S =
        lg21D6NoAccessResamplingEstimateLaw S :=
  ⟨lg21D6GaussianPBOResampling_observably_fair S,
    lg21D6ActualAccessEstimateLaw_eq_noAccessResamplingEstimateLaw S⟩

end

end LG21TestOptionalPolicies
